import { Breakpoint } from './breakpoint';

export interface ISlickSettings {
    accessibility?: boolean;
    adaptiveHeight?: boolean;
    appendArrows?: JQuery<HTMLElement>; 
    appendDots?: JQuery<HTMLElement>;
    arrows?: boolean;
    asNavFor?: JQuery<HTMLElement>;
    prevArrow?: string | HTMLElement | JQuery<HTMLElement>;
    nextArrow?: string | HTMLElement | JQuery<HTMLElement>;
    autoplay?: boolean;
    autoplaySpeed?: number;
    centerMode?: boolean;
    centerPadding?: string;
    cssEase?: 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'linear';
    customPaging?: (slider: any, i: number) => JQuery<HTMLElement>;
    dots?: boolean;
    dotsClass?: string;
    draggable?: boolean;
    easing?: 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'linear';
    edgeFriction?: number;
    fade?: boolean;
    focusOnSelect?: boolean;
    focusOnChange?: boolean;
    infinite?: boolean;
    initialSlide?: number;
    lazyLoad?: 'ondemand' | 'progressive';
    mobileFirst?: boolean;
    pauseOnHover?: boolean;
    pauseOnFocus?: boolean;
    pauseOnDotsHover?: boolean;
    respondTo?: 'min' | 'slider' | 'window';
    responsive?: Array<Breakpoint>;
    rows?: number;
    rtl?: boolean;
    slide?: string | HTMLElement;
    slidesPerRow?: number;
    slidesToShow?: number;
    slidesToScroll?: number;
    speed?: number;
    swipe?: boolean;
    swipeToSlide?: boolean;
    touchMove?: boolean;
    touchThreshold?: number;
    useCSS?: boolean;
    useTransform?: boolean;
    variableWidth?: boolean;
    vertical?: boolean;
    verticalSwiping?: boolean;
    waitForAnimate?: boolean;
    zIndex?: number;
}